# Smoke Test Log Analyser

Python tool for processing smoke test CSV data and generating structured Excel outputs and graphs.

## What it does

This project reads raw smoke test log data, filters it by date and time, extracts key test information, and exports the results into Excel these results are highlighted if outsided designated threshold(red if over orange if under),.It also generates a trigger point graph and embeds it into the output workbook.



## Features

- Tkinter GUI for file selection and run settings
- Date/time filtering with optional end range
- Excel export with structured output
- Trigger point threshold highlighting
- Embedded Matplotlib graph in Excel
- Option to write to an existing workbook or create a new one

## Tech Stack

- Python
- Pandas
- Tkinter
- OpenPyXL
- Matplotlib

## Files

- `gui.py` — GUI
- `main.py` — controller / main workflow
- `processor.py` — parsing, Excel generation, and plotting logic


## no sample files

Sample input files are not included because the original data was company-internal. Output screenshots are provided to show the structure and results generated by the tool.

## Run

python gui.py

Install dependencies:

```bash
pip install pandas openpyxl matplotlib

